# Generated by Django 4.1 on 2022-12-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_fileupload_upload_uploader_created_at_delete_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploader',
            name='cookie',
        ),
    ]
