# Generated by Django 4.1 on 2023-01-08 16:42

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_remove_uploader_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='password',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='delete_at',
            field=models.DateTimeField(default=uploader.models.maxDaysFromNow),
        ),
        migrations.AlterField(
            model_name='upload',
            name='identifier',
            field=models.CharField(default=uploader.models.generate_identifer, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
