# Generated by Django 4.1 on 2023-01-12 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_upload_password_alter_upload_delete_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uploader.upload'),
        ),
    ]
