# Generated by Django 4.1 on 2023-01-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_alter_fileupload_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='originalFileName',
            field=models.CharField(default='test.txt', max_length=80),
            preserve_default=False,
        ),
    ]
